from abc import ABC, abstractmethod
from source.domain.entities.user import UserEntity as User
from source.domain.value_objects import ID, Email


class IUserRepository(ABC):
    @abstractmethod
    async def add(self, user: User) -> User: ...
    @abstractmethod
    async def update(self, user: User) -> User | None: ...
    @abstractmethod
    async def delete(self, user: User) -> None: ...
    @abstractmethod
    async def get_by_id(self, user_id: ID) -> User | None: ...
    @abstractmethod
    async def get_by_email(self, user_email: Email) -> User | None: ...
    @abstractmethod
    async def get_by_username(self, username: str) -> User | None: ...
