"""empty message

Revision ID: e281b3d707b9
Revises: 8567afd22f8f
Create Date: 2026-05-11 14:50:52.692928

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e281b3d707b9"
down_revision: Union[str, Sequence[str], None] = "8567afd22f8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
