"""empty message

Revision ID: 8567afd22f8f
Revises: f56becb424bd
Create Date: 2026-04-17 17:45:45.784810

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8567afd22f8f"
down_revision: Union[str, Sequence[str], None] = "f56becb424bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_group_id_fkey"), "users", type_="foreignkey")
    op.create_foreign_key(
        None, "users", "groups", ["group_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("users_group_id_fkey"), "users", "groups", ["group_id"], ["id"]
    )
    # ### end Alembic commands ###
